### ISSUE TITLE
You have requested a non-existent service "messenger.senders_locator"

### ISSUE THREAD

**Issue by jhfyang** [williamrijksen/symfony-messenger-azure#2]
When trying to use your bundel after installation I keep getting this message : 

```
In ContainerBuilder.php line 1011:

  You have requested a non-existent service "messenger.senders_locator".

```
currently using symfony 4.1.4

Here is my `azure_messenger_adapter.yaml`: 

```
azure_messenger_adapter:
    azure:
        connectionString: '%env(SB_CONNECTION_STRING)%'
        subscriptionName: 'utipmq-preprod'
    messages:
        'App\Message\Notification\NotificationMessage': 'utip_notifications'
```
